version: '3'
services:
  command-test:
    build:
      context: .
      args:
        - module=command-test
    environment:
      - DATABASE_URL=jdbc:postgresql://command-db:5432/productdb?currentSchema=product
      - DATABASE_USERNAME=productadmin
      - DATABASE_PASSWORD=admin#3012
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SERVICE_PROTOCOL=http
      - SERVICE_HOST=command
      - SERVICE_PORT=8080
      - RAC_PROTOCOL=http
      - RAC_HOST=rac
      - RAC_PORT=8080
      - RAC_CLIENT_ID=rac_ro
      - RAC_CLIENT_SECRET=totvs@123
      - RAC_GRANT_TYPE=password
      - RAC_USERNAME=admin
      - RAC_PASSWORD=totvs@123
      - RAC_SCOPE=authorization_api
      - RAC_ACR_VALUES=tenant:totvs
    volumes:
      - maven-repo:/root/.m2
    networks:
      - product-network

networks:
  product-network:

volumes:
    maven-repo: