version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin#123
      - MYSQL_DATABASE=checkingAccount
      - MYSQL_USER=checkingAccountUser
      - MYSQL_PASSWORD=user#123
    networks:
      - checking-account-network
  app:
    build:
      context: .
      args:
        - SKIPTESTS=false
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:mysql://db:3306/checkingAccount
      - DATASOURCE_USERNAME=checkingAccountUser
      - DATASOURCE_PASSWORD=user#123
      - SERVICE_CUSTOMER_URI=http://localhost:8082/customers
      - SERVICE_NOTIFICATION_TRANSACTION_URI=http://localhost:8082/transactions
    networks:
      - checking-account-network
    depends_on:
      - db

networks:
  checking-account-network: