CREATE TABLE agency(
    ID VARCHAR(36) NOT NULL,
    NUMBER SMALLINT NOT NULL,
    VERSION BIGINT NOT NULL,
    CREATED_ON DATETIME NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL,
    CONSTRAINT AGENCY_PK PRIMARY KEY (ID)
);

-- CREATE TABLE document_type(
--     ID SMALLINT NOT NULL,
--     NAME VARCHAR(10) NOT NULL,
--     CONSTRAINT DOCUMENT_TYPE_PK PRIMARY KEY (ID)
-- );
--
-- INSERT INTO document_type(ID, NAME) VALUES (0, 'CPF');
-- INSERT INTO document_type(ID, NAME) VALUES (1, 'CNPJ');
--
-- CREATE TABLE custemer(
--     ID VARCHAR(36) NOT NULL,
--     NAME VARCHAR(255) NOT NULL,
--     DOCUMENT_NUMBER VARCHAR(17) NOT NULL,
--     DOCUMENT_TYPE SMALLINT NOT NULL,
--     VERSION BIGINT NOT NULL,
--     CREATED_ON DATETIME NOT NULL,
--     UPDATED_ON TIMESTAMP NOT NULL,
--     CONSTRAINT CUSTEMER_PK PRIMARY KEY (ID),
--     CONSTRAINT CUSTEMER_1_FK FOREIGN KEY (DOCUMENT_TYPE) REFERENCES document_type(ID)
-- );

CREATE TABLE account(
    ID VARCHAR(36) NOT NULL,
    CUSTEMER_ID VARCHAR(36) NOT NULL,
    AGENCY_ID VARCHAR(36) NOT NULL,
    NUMBER INT NOT NULL,
    DIGIT SMALLINT NOT NULL,
	AMOUNT DECIMAL(20, 2) NOT NULL,
    VERSION BIGINT NOT NULL,
    CREATED_ON DATETIME NOT NULL,
    UPDATED_ON TIMESTAMP NOT NULL,
	CONSTRAINT ACCOUNT_PK PRIMARY KEY (ID),
	CONSTRAINT ACCOUNT_1_FK FOREIGN KEY (AGENCY_ID) REFERENCES agency(ID)
);

CREATE TABLE financial_movement (
	ID VARCHAR(36) NOT NULL,
	ACCOUNT_FROM VARCHAR(36) NOT NULL,
	ACCOUNT_TO VARCHAR(36) NOT NULL,
	AMOUNT DECIMAL(20, 2) NOT NULL,
    VERSION BIGINT NOT NULL,
    TYPE SMALLINT NOT NULL,
    CREATED_ON DATETIME NOT NULL,
    UPDATED_ON DATETIME NOT NULL,
	CONSTRAINT FINANCIAL_MOVEMENT_PK PRIMARY KEY (ID),
	CONSTRAINT FINANCIAL_MOVEMENT_1_FK FOREIGN KEY (ACCOUNT_FROM) REFERENCES account(ID),
	CONSTRAINT FINANCIAL_MOVEMENT_2_FK FOREIGN KEY (ACCOUNT_TO) REFERENCES account(ID)
);

CREATE TABLE account_transaction(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    ACCOUNT_ID VARCHAR(36),
    CUSTEMER_ID VARCHAR(36),
    CUSTOMER_NAME VARCHAR(255),
    DOCUMENT_NUMBER VARCHAR(17),
    NUMBER INT,
    AGENCY_ID VARCHAR(36),
    DIGIT SMALLINT,
	AMOUNT DECIMAL(20, 2),
	CONSTRAINT ACCOUNT_TRANSACTION_PK PRIMARY KEY (ID)
);

CREATE TABLE transaction (
	ID VARCHAR(36) NOT NULL,
	ACCOUNT_FROM BIGINT NOT NULL,
	ACCOUNT_TO BIGINT NOT NULL,
	AMOUNT DECIMAL(20, 2) NOT NULL,
    VERSION BIGINT NOT NULL,
    CREATED_ON DATETIME NOT NULL,
    UPDATED_ON DATETIME NOT NULL,
	CONSTRAINT TRANSACTION_PK PRIMARY KEY (ID),
	CONSTRAINT TRANSACTION_1_FK FOREIGN KEY (ACCOUNT_FROM) REFERENCES account_transaction(ID),
	CONSTRAINT TRANSACTION_2_FK FOREIGN KEY (ACCOUNT_TO) REFERENCES account_transaction(ID)
);